service: weather-info-service
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  environment:
    API_KEY: ${env:API_KEY}
  lambdaHashingVersion: 20201221

functions:
  getWeather:
    handler: src/lambda.handler
    description: Fetches weather information based on the provided location.
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

